import {
  AccelerometerScreen,
  AmplitudeScreen,
  AssetScreen,
  AudioScreen,
  BlurView1Screen,
  BlurView2Screen,
  BrightnessScreen,
  CameraScreen,
  ConstantsScreen,
  FacebookScreen,
  FirebaseAuthTestScreen,
  FontScreen,
  GithubScreen,
  GoogleScreen,
  GoogleSignInScreen,
  GyroscopeScreen,
  HomeScreen,
  LinearGradientScreen,
  LinksScreen,
  LocalAuthenticationScreen,
  MainScreen,
  ManifestScreen,
  MapViewScreen,
  PlatformScreen,
  PostsScreen,
  SettingsScreen,
  SvgScreen,
  SystemFontsScreen,
  VectorIconsScreen,
} from '../screens'

const RouteConfig = {
  Main: MainScreen,
  Accelerometer: AccelerometerScreen,
  Amplitude: AmplitudeScreen,
  Asset: AssetScreen,
  Audio: AudioScreen,
  BlurView1: BlurView1Screen,
  BlurView2: BlurView2Screen,
  Brightness: BrightnessScreen,
  Camera: CameraScreen,
  Constants: ConstantsScreen,
  Facebook: FacebookScreen,
  FirebaseAuthTest: FirebaseAuthTestScreen,
  Font: FontScreen,
  Github: GithubScreen,
  Google: GoogleScreen,
  GoogleSignIn: GoogleSignInScreen,
  Gyroscope: GyroscopeScreen,
  Home: HomeScreen,
  LinearGradient: LinearGradientScreen,
  Links: LinksScreen,
  LocalAuthentication: LocalAuthenticationScreen,
  Manifest: ManifestScreen,
  MapView: MapViewScreen,
  Platform: PlatformScreen,
  Posts: PostsScreen,
  Settings: SettingsScreen,
  Svg: SvgScreen,
  SystemFonts: SystemFontsScreen,
  VectorIcons: VectorIconsScreen,
}

export default RouteConfig
